### ISSUE TITLE
我发现裁剪后比原图大

### ISSUE THREAD

**Issue by puyide** [yanue/nginx-lua-GraphicsMagick#1]
如果一个图500X500 打开原图80k左右，如果后面根裁剪参数照样500X500 的分辨率居然比原图大，而且有时候400_400 都比原图500_500 的图像存储大小大！你们遇到这样的情况吗？

**Comment by yanue** [comment]
是有这种情况的
`
-- 由于压缩后比较模糊,默认图片质量为100,请根据自己情况修改quality
cmd = cmd .. " -quality 100"
`
你可以改这个参数试下
